global using System;
global using MediatR;
global using Npgsql;
global using System.Data;
global using Daco.Domain.Common;
global using Daco.Infrastructure.Persistence.Common;
global using Microsoft.Extensions.Logging;
global using Daco.Application.Common.Interfaces;
global using Dapper;
global using Daco.Infrastructure.Persistence.EventDispatching;
global using Daco.Infrastructure.Persistence.UnitOfWork;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Configuration;
global using Daco.Domain.Users.Aggregates;
global using Daco.Domain.Users.Entities;
global using Daco.Application.Common.Validators;
global using Daco.Infrastructure.Persistence.Repositories;
global using Daco.Infrastructure.Services.Authentication;
global using Daco.Infrastructure.Services.Notifications;
global using Daco.Infrastructure.Services.Security;
global using static Daco.Infrastructure.Constants;
global using Daco.Infrastructure.Persistence.Models.DTOs;
global using Daco.Domain.Users.Enums;
global using Daco.Infrastructure.Persistence.Mappings.Users;

